"""End-to-end coverage of every TxPlan intent through the native library.

The fixtures in ``test-fixtures/quicktx-intents/`` are generated by the JVM QuickTxIntentsTest via
``TxPlan.from(tx).toYaml()`` (CCL's exact intent shapes); here each one is built through the native
library via the Python wrapper. Mirrors the Go ``intents_test.go`` for cross-wrapper parity.
"""
import glob
from pathlib import Path

import pytest

from ccl._ffi import CclError
from ccl.network import Network

FIXTURES = Path(__file__).resolve().parents[3] / "test-fixtures" / "quicktx-intents"

# The fee_payer baked into the fixtures (derived from the core test mnemonic), and the deterministic
# always-succeeds-V2 script address + datum hash used by the Plutus spend fixture.
SENDER = "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp"
SENDER2 = "addr_test1qz7svwszky8gcmhrfza7a89z9u0dfzd3l7h23sqlc5yml7ejcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwqcqrvr0"
SCRIPT_ADDR = "addr_test1wpunlryvl7aqsxe22erzlsseej87v5kk5vutvtrmzdy8dect48z0w"
SCRIPT_DATUM_HASH = "9e1199a988ba72ffd6e9c269cadb3b53b5f360ff99f112d9b2ee30c4d74ad88b"
SCRIPT_TX_HASH = "b" * 64
EXEC_UNITS = [{"mem": 2000000, "steps": 500000000}]

# Protocol parameters incl. the Conway deposits the governance/staking/pool intents need.
PROTOCOL_PARAMS = {
    "min_fee_a": 44, "min_fee_b": 155381, "max_tx_size": 16384, "max_val_size": "5000",
    "key_deposit": "2000000", "pool_deposit": "500000000", "drep_deposit": "2000000",
    "gov_action_deposit": "1000000000", "coins_per_utxo_size": "4310",
    "max_tx_ex_mem": "14000000", "max_tx_ex_steps": "10000000000",
    "price_mem": 0.0577, "price_step": 0.0000721, "collateral_percent": 150,
    "max_collateral_inputs": 3, "min_fee_ref_script_cost_per_byte": 15,
}


def _utxos():
    # A 2000-ADA UTXO (covers the gov-action deposit) + a small one for the reference-input fixture.
    return [
        {"tx_hash": "a" * 64, "output_index": 0, "address": SENDER,
         "amount": [{"unit": "lovelace", "quantity": "2000000000"}]},
        {"tx_hash": "c" * 64, "output_index": 0, "address": SENDER,
         "amount": [{"unit": "lovelace", "quantity": "5000000"}]},
        {"tx_hash": "a" * 64, "output_index": 1, "address": SENDER2,
         "amount": [{"unit": "lovelace", "quantity": "2000000000"}]},
    ]


def _assert_built(result):
    assert len(result["tx_cbor"]) > 0
    assert len(result["tx_hash"]) == 64
    assert int(result["fee"]) > 0


@pytest.mark.parametrize("fixture", sorted(glob.glob(str(FIXTURES / "*.yaml"))),
                         ids=lambda p: Path(p).stem)
def test_intent_builds(ccl, fixture):
    yaml = Path(fixture).read_text()
    _assert_built(ccl.quicktx.build(yaml, _utxos(), PROTOCOL_PARAMS))


# The mnemonic the fixtures are derived from (account 0/0 == SENDER).
INTENT_MNEMONIC = "test walk nut penalty hip pave soap entry language right filter choice"


def test_sign_with_stake_key(ccl):
    # A stake registration must be witnessed by the stake key too; the stake role adds it.
    yaml = (FIXTURES / "stake_registration.yaml").read_text()
    utxos = [{"tx_hash": "a" * 64, "output_index": 0, "address": SENDER,
              "amount": [{"unit": "lovelace", "quantity": "2000000000"}]}]
    built = ccl.quicktx.build(yaml, utxos, PROTOCOL_PARAMS)

    from ccl import SigningRole
    with ccl.accounts.from_mnemonic(INTENT_MNEMONIC, Network.TESTNET) as acct:
        signed_payment = acct.sign_tx(built["tx_cbor"])
        signed_stake = acct.sign_tx(built["tx_cbor"], SigningRole.PAYMENT | SigningRole.STAKE)
    assert len(signed_stake) > len(signed_payment)


def test_plutus_mint(ccl):
    yaml = (FIXTURES / "plutus" / "script_minting.yaml").read_text()
    utxos = [{"tx_hash": "a" * 64, "output_index": 0, "address": SENDER,
              "amount": [{"unit": "lovelace", "quantity": "2000000000"}]}]
    _assert_built(ccl.quicktx.build(yaml, utxos, PROTOCOL_PARAMS, exec_units=EXEC_UNITS))
    with pytest.raises(CclError):
        ccl.quicktx.build(yaml, utxos, PROTOCOL_PARAMS)


def test_plutus_spend(ccl):
    yaml = (FIXTURES / "plutus" / "script_collect_from.yaml").read_text()
    utxos = [
        {"tx_hash": SCRIPT_TX_HASH, "output_index": 0, "address": SCRIPT_ADDR,
         "amount": [{"unit": "lovelace", "quantity": "10000000"}], "data_hash": SCRIPT_DATUM_HASH},
        {"tx_hash": "a" * 64, "output_index": 0, "address": SENDER,
         "amount": [{"unit": "lovelace", "quantity": "2000000000"}]},
    ]
    _assert_built(ccl.quicktx.build(yaml, utxos, PROTOCOL_PARAMS, exec_units=EXEC_UNITS))
    with pytest.raises(CclError):
        ccl.quicktx.build(yaml, utxos, PROTOCOL_PARAMS)
