package com.bloxbean.cardano.bridge;

import com.bloxbean.cardano.bridge.util.ErrorState;
import com.bloxbean.cardano.bridge.util.NativeString;
import com.bloxbean.cardano.bridge.util.ResultState;
import org.graalvm.nativeimage.IsolateThread;
import org.graalvm.nativeimage.UnmanagedMemory;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.c.type.CCharPointer;

/**
 * Core lifecycle and result-retrieval entry points of the Cardano Client Bindings native library.
 *
 * <h2>What this library is</h2>
 * The Cardano Client Bindings compiles <a href="https://github.com/bloxbean/cardano-client-lib">Cardano
 * Client Lib</a> into a native shared library ({@code libccl.so} / {@code .dylib} / {@code .dll})
 * with GraalVM {@code native-image}, exposing CCL's <em>offline</em> Cardano operations through a
 * flat C ABI. Every public function in this package is a GraalVM {@link CEntryPoint}, i.e. an
 * exported C symbol callable from any language with an FFI (Python, Go, Rust, JavaScript, C).
 *
 * <h2>Calling convention</h2>
 * All entry points follow the same contract, because only C-compatible primitives can cross the
 * boundary (no Java objects):
 * <ul>
 *   <li><b>First parameter</b> is always an {@link IsolateThread} — the handle returned by
 *       {@code graal_create_isolate} (or {@code graal_attach_thread}). It identifies the GraalVM
 *       isolate (managed heap) and the thread the call runs on.</li>
 *   <li><b>Inputs</b> are C primitives ({@code int}) and null-terminated UTF-8 C strings
 *       ({@link CCharPointer}); structured input is passed as a JSON string.</li>
 *   <li><b>Return value</b> is an {@code int} status code from {@link ErrorCodes}
 *       ({@code 0} = success, negative = error).</li>
 *   <li><b>The actual result</b> (when there is one) is <em>not</em> returned directly. It is
 *       stored in thread-local state and retrieved with a follow-up call to
 *       {@link #getResult(IsolateThread) ccl_get_result}. Results are JSON strings (or a bare
 *       value such as a hex string, depending on the function).</li>
 *   <li><b>On error</b>, a human-readable message is stored thread-local and retrieved with
 *       {@link #getLastError(IsolateThread) ccl_get_last_error}.</li>
 *   <li><b>Returned strings</b> are allocated in unmanaged (malloc'd) memory and <em>must</em> be
 *       released by the caller with {@link #freeString(IsolateThread, CCharPointer) ccl_free_string}.</li>
 * </ul>
 *
 * <h2>Typical sequence (per logical operation)</h2>
 * <pre>{@code
 *   int rc = ccl_address_info(thread, address);        // 1. do the work; returns status
 *   if (rc == 0) {
 *       char* json = ccl_get_result(thread);           // 2. fetch JSON result (thread-local)
 *       // ... use json ...
 *       ccl_free_string(thread, json);                 // 3. release the malloc'd string
 *   } else {
 *       char* err = ccl_get_last_error(thread);        // or fetch the error message
 *       ccl_free_string(thread, err);
 *   }
 * }</pre>
 *
 * <p>The result slot is <b>read-once</b>: {@code ccl_get_result} consumes the value, and a second
 * read returns an empty string — copy it if you need it twice. (Deliberate: results can carry
 * secrets, e.g. an exported recovery phrase, which must not linger.)
 *
 * <p>Because the result/error are thread-local, the work call and its {@code ccl_get_result} /
 * {@code ccl_get_last_error} retrieval must run on the same isolate thread.
 *
 * @see ErrorCodes status codes returned by every entry point
 */
public final class CclBridge {

    // Single-sourced from the Gradle project version at build time (see BuildInfo, generated by
    // core/build.gradle) so the native lib and the wrappers can never silently disagree on version.
    private static final String VERSION = BuildInfo.VERSION;

    private CclBridge() {}

    /**
     * Returns the Cardano Client Bindings library version.
     *
     * <p>Exported as {@code ccl_version}. On success the version string (e.g. {@code "0.1.0"}) is
     * placed in the thread-local result; retrieve it with
     * {@link #getResult(IsolateThread) ccl_get_result}.
     *
     * @param thread the current isolate thread
     * @return {@link ErrorCodes#CCL_SUCCESS}
     */
    @CEntryPoint(name = "ccl_version")
    public static int version(IsolateThread thread) {
        ResultState.set(VERSION);
        return ErrorCodes.CCL_SUCCESS;
    }

    /**
     * Returns the result string produced by the most recent successful call on this thread —
     * <b>read-once</b>: fetching the result consumes it, and a second read returns an empty
     * string. Read-once is deliberate (results can carry secrets, e.g. an exported recovery
     * phrase, which must not linger in the slot); copy the string if you need it twice.
     *
     * <p>Exported as {@code ccl_get_result}. The returned pointer is malloc'd and owned by the
     * caller, who must release it with {@link #freeString(IsolateThread, CCharPointer) ccl_free_string}.
     * If no result is set, an empty string is returned (never {@code NULL}).
     *
     * @param thread the current isolate thread
     * @return a newly allocated, null-terminated UTF-8 C string holding the result (often JSON)
     */
    @CEntryPoint(name = "ccl_get_result")
    public static CCharPointer getResult(IsolateThread thread) {
        String result = ResultState.get();
        if (result == null) {
            return NativeString.toCString("");
        }
        return NativeString.toCString(result);
    }

    /**
     * Returns the error message produced by the most recent failed call on this thread.
     *
     * <p>Exported as {@code ccl_get_last_error}. Call this after an entry point returns a negative
     * {@link ErrorCodes status code}. The returned pointer is malloc'd and owned by the caller, who
     * must release it with {@link #freeString(IsolateThread, CCharPointer) ccl_free_string}. If no
     * error is set, an empty string is returned (never {@code NULL}).
     *
     * @param thread the current isolate thread
     * @return a newly allocated, null-terminated UTF-8 C string holding the error message
     */
    @CEntryPoint(name = "ccl_get_last_error")
    public static CCharPointer getLastError(IsolateThread thread) {
        String error = ErrorState.get();
        if (error == null) {
            return NativeString.toCString("");
        }
        return NativeString.toCString(error);
    }

    /**
     * Frees a string previously returned by this library.
     *
     * <p>Exported as {@code ccl_free_string}. Every non-{@code NULL} pointer returned by
     * {@code ccl_get_result} / {@code ccl_get_last_error} is allocated in unmanaged memory and
     * <em>must</em> be passed here exactly once to avoid a memory leak. Passing {@code NULL} is a
     * safe no-op.
     *
     * @param thread the current isolate thread
     * @param ptr    the string pointer to release (may be {@code NULL})
     */
    @CEntryPoint(name = "ccl_free_string")
    public static void freeString(IsolateThread thread, CCharPointer ptr) {
        if (ptr.isNonNull()) {
            UnmanagedMemory.free(ptr);
        }
    }
}
