package mesmo

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// The fee_payer/from address baked into the testdata/intents/*.yaml fixtures (derived from the
// core test mnemonic). The fixtures are generated by the JVM QuickTxIntentsTest via
// TxPlan.from(tx).toYaml(), so they carry CCL's exact intent YAML shapes; here we drive each one
// through the native library end-to-end to prove the lib builds it offline (and that the
// native-image reflection config covers the governance/staking/DRep classes).
const intentSender = "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp"

// Second sender used by the compose fixture (multiple senders into one transaction).
const intentSender2 = "addr_test1qz7svwszky8gcmhrfza7a89z9u0dfzd3l7h23sqlc5yml7ejcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwqcqrvr0"

func TestQuickTxIntentsE2E(t *testing.T) {
	files, err := filepath.Glob("../../../test-fixtures/quicktx-intents/*.yaml")
	if err != nil {
		t.Fatalf("glob fixtures: %v", err)
	}
	if len(files) == 0 {
		t.Fatal("no intent fixtures found in testdata/intents/")
	}

	// A 2000-ADA UTXO at the sender (covers the largest deposit — gov action = 1000 ADA) plus a
	// small one that the reference-input fixture reads.
	utxos := []map[string]interface{}{
		{
			"tx_hash":      strings.Repeat("a", 64),
			"output_index": 0,
			"address":      intentSender,
			"amount":       []map[string]interface{}{{"unit": "lovelace", "quantity": "2000000000"}},
		},
		{
			"tx_hash":      strings.Repeat("c", 64),
			"output_index": 0,
			"address":      intentSender,
			"amount":       []map[string]interface{}{{"unit": "lovelace", "quantity": "5000000"}},
		},
		{
			"tx_hash":      strings.Repeat("a", 64),
			"output_index": 1,
			"address":      intentSender2,
			"amount":       []map[string]interface{}{{"unit": "lovelace", "quantity": "2000000000"}},
		},
	}

	for _, f := range files {
		name := strings.TrimSuffix(filepath.Base(f), ".yaml")
		t.Run(name, func(t *testing.T) {
			yamlBytes, err := os.ReadFile(f)
			if err != nil {
				t.Fatalf("read %s: %v", f, err)
			}
			result, err := lib.QuickTx.Build(string(yamlBytes), utxos, testProtocolParams(), 1)
			if err != nil {
				t.Fatalf("build %s: %v", name, err)
			}
			if len(result.TxCbor) == 0 {
				t.Error("tx_cbor should not be empty")
			}
			if len(result.TxHash) != 64 {
				t.Errorf("expected 64-char tx_hash, got %d", len(result.TxHash))
			}
			if fee, err := strconv.Atoi(result.Fee); err != nil || fee <= 0 {
				t.Errorf("expected positive fee, got %q", result.Fee)
			}
		})
	}
}
