package mesmo

import (
	"os"
	"strings"
	"testing"
)

// End-to-end Plutus script spend (script_collect_from) through the native lib via Go. Unlike the
// generic intent table, this one needs a UTXO at the script address (with the datum hash) plus a
// fee/collateral UTXO, and caller-supplied execution units for the spend redeemer. The fixture is
// generated by QuickTxIntentsTest.scriptCollectFrom; the script address + datum hash below are the
// deterministic values for the always-succeeds V2 validator and datum int(42).
const (
	scriptAddr     = "addr_test1wpunlryvl7aqsxe22erzlsseej87v5kk5vutvtrmzdy8dect48z0w"
	scriptDatumHsh = "9e1199a988ba72ffd6e9c269cadb3b53b5f360ff99f112d9b2ee30c4d74ad88b"
	scriptTxHash   = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
)

func TestQuickTxScriptSpendE2E(t *testing.T) {
	yamlBytes, err := os.ReadFile("../../../test-fixtures/quicktx-intents/plutus/script_collect_from.yaml")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	yaml := string(yamlBytes)

	// The script UTXO to spend (with its datum hash) + a fee/collateral UTXO at the sender.
	utxos := []map[string]interface{}{
		{
			"tx_hash":      scriptTxHash,
			"output_index": 0,
			"address":      scriptAddr,
			"amount":       []map[string]interface{}{{"unit": "lovelace", "quantity": "10000000"}},
			"data_hash":    scriptDatumHsh,
		},
		{
			"tx_hash":      strings.Repeat("a", 64),
			"output_index": 0,
			"address":      intentSender,
			"amount":       []map[string]interface{}{{"unit": "lovelace", "quantity": "2000000000"}},
		},
	}
	execUnits := []map[string]interface{}{{"mem": 2000000, "steps": 500000000}}

	// With execution units: builds.
	result, err := bridge.QuickTx.Build(yaml, utxos, testProtocolParams(), 0, execUnits)
	if err != nil {
		t.Fatalf("script spend build failed: %v", err)
	}
	if len(result.TxCbor) == 0 || len(result.TxHash) != 64 {
		t.Errorf("bad result: cbor=%d hash=%d", len(result.TxCbor), len(result.TxHash))
	}

	// Without execution units: the script can't be costed, so the build must fail.
	if _, err := bridge.QuickTx.Build(yaml, utxos, testProtocolParams(), 0); err == nil {
		t.Error("expected script spend to fail without execution units")
	}
}

// End-to-end Plutus script mint (script_minting). Only needs a fee/collateral UTXO at the sender
// plus the redeemer's execution units.
func TestQuickTxScriptMintE2E(t *testing.T) {
	yamlBytes, err := os.ReadFile("../../../test-fixtures/quicktx-intents/plutus/script_minting.yaml")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	yaml := string(yamlBytes)

	utxos := []map[string]interface{}{{
		"tx_hash":      strings.Repeat("a", 64),
		"output_index": 0,
		"address":      intentSender,
		"amount":       []map[string]interface{}{{"unit": "lovelace", "quantity": "2000000000"}},
	}}
	execUnits := []map[string]interface{}{{"mem": 2000000, "steps": 500000000}}

	result, err := bridge.QuickTx.Build(yaml, utxos, testProtocolParams(), 0, execUnits)
	if err != nil {
		t.Fatalf("script mint build failed: %v", err)
	}
	if len(result.TxCbor) == 0 || len(result.TxHash) != 64 {
		t.Errorf("bad result: cbor=%d hash=%d", len(result.TxCbor), len(result.TxHash))
	}

	if _, err := bridge.QuickTx.Build(yaml, utxos, testProtocolParams(), 0); err == nil {
		t.Error("expected script mint to fail without execution units")
	}
}
