// End-to-end coverage of every TxPlan intent through the native library.
//
// The fixtures in test-fixtures/quicktx-intents/ are generated by the JVM QuickTxIntentsTest via
// TxPlan.from(tx).toYaml(); here each is built through the native library via the JS wrapper.
// Mirrors the Go intents_test.go for cross-wrapper parity.

import { describe, it, expect, beforeAll, afterAll } from "bun:test";
import { MesmoBridge } from "../src/index.js";
import { readdirSync, readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), "../../../test-fixtures/quicktx-intents");

const SENDER = "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp";
const SENDER2 = "addr_test1qz7svwszky8gcmhrfza7a89z9u0dfzd3l7h23sqlc5yml7ejcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwqcqrvr0";
const SCRIPT_ADDR = "addr_test1wpunlryvl7aqsxe22erzlsseej87v5kk5vutvtrmzdy8dect48z0w";
const SCRIPT_DATUM_HASH = "9e1199a988ba72ffd6e9c269cadb3b53b5f360ff99f112d9b2ee30c4d74ad88b";
const SCRIPT_TX_HASH = "b".repeat(64);
const EXEC_UNITS = [{ mem: 2000000, steps: 500000000 }];

// Protocol parameters incl. the Conway deposits the governance/staking/pool intents need.
const PROTOCOL_PARAMS = {
  min_fee_a: 44, min_fee_b: 155381, max_tx_size: 16384, max_val_size: "5000",
  key_deposit: "2000000", pool_deposit: "500000000", drep_deposit: "2000000",
  gov_action_deposit: "1000000000", coins_per_utxo_size: "4310",
  max_tx_ex_mem: "14000000", max_tx_ex_steps: "10000000000",
  price_mem: 0.0577, price_step: 0.0000721, collateral_percent: 150,
  max_collateral_inputs: 3, min_fee_ref_script_cost_per_byte: 15,
};

function utxos() {
  return [
    { tx_hash: "a".repeat(64), output_index: 0, address: SENDER,
      amount: [{ unit: "lovelace", quantity: "2000000000" }] },
    { tx_hash: "c".repeat(64), output_index: 0, address: SENDER,
      amount: [{ unit: "lovelace", quantity: "5000000" }] },
    { tx_hash: "a".repeat(64), output_index: 1, address: SENDER2,
      amount: [{ unit: "lovelace", quantity: "2000000000" }] },
  ];
}

// A successfully built tx: non-empty CBOR, a 64-char hash, and a positive fee. Mirrors the Python
// reference's _assert_built so the wrappers assert the same shape.
function assertBuilt(result) {
  expect(result.tx_cbor.length).toBeGreaterThan(0);
  expect(result.tx_hash.length).toBe(64);
  expect(Number(result.fee)).toBeGreaterThan(0);
}

describe("QuickTx intents E2E", () => {
  let bridge;
  beforeAll(() => { bridge = new MesmoBridge(); });
  afterAll(() => { if (bridge) bridge.close(); });

  const fixtures = readdirSync(FIXTURES).filter((f) => f.endsWith(".yaml")).sort();

  for (const f of fixtures) {
    it(`builds ${f.replace(".yaml", "")}`, () => {
      const yaml = readFileSync(join(FIXTURES, f), "utf8");
      assertBuilt(bridge.quicktx.build(yaml, utxos(), PROTOCOL_PARAMS));
    });
  }

  // --- Plutus / script paths (the plutus/ sub-directory, not covered by the top-level loop) ---

  it("builds a Plutus mint with execution units", () => {
    const yaml = readFileSync(join(FIXTURES, "plutus", "script_minting.yaml"), "utf8");
    const u = [{ tx_hash: "a".repeat(64), output_index: 0, address: SENDER,
                 amount: [{ unit: "lovelace", quantity: "2000000000" }] }];
    assertBuilt(bridge.quicktx.build(yaml, u, PROTOCOL_PARAMS, EXEC_UNITS));
    // The Plutus path requires caller-supplied exec units; without them the build is rejected.
    expect(() => bridge.quicktx.build(yaml, u, PROTOCOL_PARAMS)).toThrow();
  });

  it("builds a Plutus spend with execution units", () => {
    const yaml = readFileSync(join(FIXTURES, "plutus", "script_collect_from.yaml"), "utf8");
    const u = [
      { tx_hash: SCRIPT_TX_HASH, output_index: 0, address: SCRIPT_ADDR,
        amount: [{ unit: "lovelace", quantity: "10000000" }], data_hash: SCRIPT_DATUM_HASH },
      { tx_hash: "a".repeat(64), output_index: 0, address: SENDER,
        amount: [{ unit: "lovelace", quantity: "2000000000" }] },
    ];
    assertBuilt(bridge.quicktx.build(yaml, u, PROTOCOL_PARAMS, EXEC_UNITS));
    expect(() => bridge.quicktx.build(yaml, u, PROTOCOL_PARAMS)).toThrow();
  });

  it("builds a Plutus lock (pay to a script address with a datum hash)", () => {
    // Locking funds at a script address is a plain payment carrying a datum hash — no script runs,
    // so no exec units are required (unlike the spend that later unlocks it).
    const yaml = readFileSync(join(FIXTURES, "plutus", "plutus_lock.yaml"), "utf8");
    assertBuilt(bridge.quicktx.build(yaml, utxos(), PROTOCOL_PARAMS));
  });

  it("derives the datum hash the lock fixture commits to", () => {
    // plutus_lock.yaml locks under datum_hash 9e1199… — the Plutus data hash of the integer 42
    // (CBOR 182a). Assert the bridge computes the exact value the fixture embeds, tying the
    // plutus.dataHash primitive to the on-fixture datum.
    expect(bridge.plutus.dataHash("182a")).toBe(SCRIPT_DATUM_HASH);
  });
});
